### ISSUE TITLE
Release fork as portable/zip-version

### ISSUE THREAD

**Issue by ctcDNightmare** [HoneyHazard/PixelMatchSwitcher#8]
Would it be possible to release the obs-fork+plugin maybe also as portable/zip version so we can just extract it side-by-side with other instances?

**Comment by HoneyHazard** [comment]
Hello! I will probably update the latest release to include that. I went back and forth with sharing OBS installation path and settled on keeping it same, so that it's easier for users to install additional plugins. Yes, you are right, it will be helpful to also have a zip.

You could, in the meantime, open one of the installer exe's in 7zip file manager and manually extract the files somewhere

**Comment by HoneyHazard** [comment]
I've updated the release to include the win64 zip, which should be barebones and will include only a few plugins.

Let me know if this works!

https://github.com/HoneyHazard/PixelMatchSwitcher/releases/tag/0.31.8-alpha

**Comment by cyborgman007** [comment]
This works fine!

**Comment by PDXzzzz** [comment]
> 我已经更新了版本以包含win64 zip，它应该是准系统，并且只包含几个插件。
> 
> 让我知道这是否有效！
> 
> https://github.com/HoneyHazard/PixelMatchSwitcher/releases/tag/0.31.8-alpha

obs crashed ：(
